#!/usr/bin/env bash
# this is a hello world!
# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx
# Ensure Nginx is started
sudo service nginx start
sudo ufw allow 'nginx HTTP'
#backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
#hello world
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
