#!/usr/bin/env bash
# Function to add or update an entry in /etc/hosts,localhost,facebook

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
