#!/usr/bin/env bash
# this is id.
# Assign the first parameter to a variable
USERNAME=$1

# Run the whoami command as the specified user
sudo -u "$USERNAME" whoami

# Check if the command was successful
if [ "$?" -eq 0 ]; then
    echo "Command executed successfully."
else
    echo "Failed to run whoami as $USERNAME."
    exit 1
fi
