#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sed -i 's/^user \([^;]*\);.*/user nginx\1/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /var/www /etc/nginx
service nginx restart

